import { ComboBox } from "std-widgets.slint";
import { DisplayListView } from "./displays.slint";

export component Menu inherits Rectangle {
    in property <[string]> displays;
    in-out property <int> displays_selected_index;
    height: 44px;
    background: #3a3a3a;

    DisplayListView {
        displays: root.displays;
        displays_selected_index <=> root.displays_selected_index;
    }

    // TODO здесь будет выбор окон

}