
import { Menu } from "header/menu.slint";
import { BodyView } from "content/body.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "GAME APP";

    in property <[string]> titles;
    callback request_titles();
    callback window_selected(index: int);

    property <bool> show_modal: false;

    VerticalLayout {
        spacing: 0px;

        Menu {
            select_clicked => {
                root.request_titles();
                root.show_modal = true;
            }
        }

        BodyView {
            show_modal: root.show_modal;
            titles: root.titles;

            item_selected(index) => {
                root.window_selected(index);
                root.show_modal = false;
            }
        }
    }
}