import { Button } from "std-widgets.slint";
export component Menu inherits Rectangle {
    height: 44px;
    background: #3a3a3a;

    callback select_clicked();

    HorizontalLayout {
        spacing: 12px;
        padding-left: 12px;
        padding-right: 12px;

        Text {
            text: "SOME TEXT";
            color: #ff9800;
            font-size: 18px;
            vertical-alignment: center;
        }

        Button {
            text: "Select Window";
            clicked => select_clicked();
        }
    }
}