import { ComboBox } from "std-widgets.slint";

export component Menu inherits Rectangle {
    height: 44px;
    background: #3a3a3a;    

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 12px;

        Rectangle { width: 1px; }

        Text {
            text: "SOME TEXT";
            color:  #ff9800;
            font-size: 18px;
            vertical-alignment: center;
        }
    }

}