// https://docs.slint.dev/latest/docs/slint/
// for preview palitra: Slint: Show Preview
import { Menu } from "./header/menu.slint";
import { BodyView } from "./content/body.slint";

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "GAME APP";

    in property <[string]> displays;
    in-out property <int> displays_selected_index: 0;

    VerticalLayout {
        spacing: 0px;

        Menu {
            displays: root.displays;
            displays_selected_index <=> root.displays_selected_index;
        }

        BodyView {}
    }
}
